/**
 * Writes src/version.ts from package.json so bundled CLI does not require package.json at runtime.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
if (!pkg.version) {
  console.error("sync-version: package.json missing version");
  process.exit(1);
}

const out = join(root, "src", "version.ts");
writeFileSync(
  out,
  `/** Auto-generated by scripts/sync-version.mjs — do not edit */\nexport const PACKAGE_VERSION = ${JSON.stringify(pkg.version)};\n`,
  "utf8"
);
console.log(`sync-version: ${pkg.version}`);